config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations:      "users/registrations",
      sessions:           "users/sessions",
      passwords:          "users/passwords"
    }

  root to: 'users#sign_in'

  get '/index' => 'home#index', as: :home

  get '/auditions/:year/:month_name'     => 'auditions#filter', as: :filter_audition
  get '/auditions/:year/:month_name/new' => 'auditions#new', as: :new_audition
  resources :auditions, except: :new

  resources :prosecutors
  resources :months
end

app/models/month.rb
class Month < ActiveRecord::Base
  belongs_to :user
  has_many :auditions
end

app/controllers/months_controller.rb
class MonthsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_month, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @months = @current_user.months.all
    respond_with(@months)
  end

  def show
    respond_with(@month)
  end

  def new
    @month = Month.new
    respond_with(@month)
  end

  def edit
  end

  def create
    @month = Month.new(month_params)
    @month.user = @current_user

    @month.save
    respond_with(@month)
  end

  def update
    @month.update(month_params)
    respond_with(@month)
  end

  def destroy
    @month.destroy
    respond_with(@month)
  end

  private
    def set_month
      @month = @current_user.months.find(params[:id])
    end

    def month_params
      params.require(:month).permit(:name, :year)
    end
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/views/months/_form.html.erb
<%= form_for(@month) do |f| %>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name, placeholder: 'ex: julho' %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.text_field :year, placeholder: 'ex: 2016' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/months/edit.html.erb
<h1>Editing month</h1>

<%= render 'form' %>

<%= link_to 'Show', @month %> |
<%= link_to 'Back', months_path %>

app/views/months/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"> Listando meses</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Year</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @months.each do |month| %>
          <tr>
            <td><%= month.name %></td>
            <td><%= month.year %></td>
            <td><%= link_to 'Show', month %></td>
            <td><%= link_to 'Edit', edit_month_path(month) %></td>
            <td><%= link_to 'Destroy', month, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

<%= button_to 'Adicionar', new_month_path, class: 'btn btn-success', method: :get %>

app/views/months/new.html.erb
<h1>Novo mês</h1>

<%= render 'form' %>

app/views/months/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @month.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @month.year %>
</p>

<%= link_to 'Edit', edit_month_path(@month) %> |
<%= link_to 'Back', months_path %>