config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations:      "users/registrations",
      sessions:           "users/sessions",
      passwords:          "users/passwords"
    }

  root to: 'users#sign_in'

  get '/index' => 'home#index', as: :home

  get '/auditions/:year/:month_name'     => 'auditions#filter', as: :filter_audition
  get '/auditions/:year/:month_name/new' => 'auditions#new', as: :new_audition
  resources :auditions, except: :new

  resources :prosecutors
  resources :months
end

app/models/audition.rb
class Audition < ActiveRecord::Base
  belongs_to :prosecutor
  belongs_to :month
  belongs_to :user

  delegate :name, to: :prosecutor, prefix: true
  delegate :name, to: :month, prefix: true

  scope :by_month, lambda { |month| where('extract(month from date) = ?', month) }
end

app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prosecutor, only: [:new]
  before_action :set_audition, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @auditions = @current_user.auditions.all
    respond_with(@auditions)
  end

  def show
    respond_with(@audition)
  end

  def new
    @audition = Audition.new

    respond_with(@audition)
  end

  def edit
  end

  def create
    @audition = Audition.new(audition_params)
    @audition.month = Month.select(:id, :name).find_by(name: params[:audition][:month_name], year: params[:audition][:year])
    @audition.user = @current_user

    @audition.save
    respond_with(@audition)
  end

  def update
    @audition.update(audition_params)
    respond_with(@audition)
  end

  def destroy
    @audition.destroy
    redirect_to filter_audition_path(year: @year, month_name: ( l @date, format: :month ))
  end

  def filter
    year = params[:year]
    month_name = params[:month_name].downcase
    @month     = @current_user.months.find_by(name: month_name, year: year)

    t('date.month_names').length.times do |index|
      if (t('date.month_names')[index] == @month.name.capitalize) && !(t('date.month_names')[index].nil?)
        @month_num = index
      end
    end

    @auditions = @current_user.auditions.by_month(@month_num)
  end

  private
    def set_audition
      @audition = @current_user.auditions.find(params[:id])
    end

    def set_prosecutor
      @prosecutor = @current_user.prosecutors.all
    end

    def audition_params
      params.require(:audition).permit(:courte, :turn, :date, :prosecutor_id)
    end
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/views/auditions/_form.html.erb
<%= form_for(@audition) do |f| %>
  <div class="field">
    <%= f.label :procurador %><br>
    <%= f.select :prosecutor_id, @prosecutor.map{|pr| [pr.name, pr.id]} %>
  </div>
  <div class="field">
    <%= f.label :vara %><br>
    <%= f.select :courte, [['1ª vara', '1ª vara'], ['2ª vara', '2ª vara']] %>
  </div>
  <div class="field">
    <%= f.label :turno %><br>
    <%= f.select :turn, [['Manhã', 'manhã'], ['Tarde', 'tarde']] %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.date_select :date %>
  </div>

  <%= hidden_field :audition, :month_name, value: params[:month_name] %>
  <%= hidden_field :audition, :year, value: params[:year] %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auditions/edit.html.erb
<h1>Editing audition</h1>

<%= render 'form' %>

<%= link_to 'Show', @audition %> |
<%= link_to 'Back', auditions_path %>

app/views/auditions/filter.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">
      Mostrando audiências de <%= @month.name.capitalize %> de <%= @month.year %>
    </h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Procurador</th>
          <th>Vara</th>
          <th>Turno</th>
          <th>Data</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <%- @auditions.each do |audition| %>
          <tr>
            <td><%= audition.prosecutor_name %></td>
            <td><%= audition.courte %></td>
            <td><%= audition.turn %></td>
            <td><%= l audition.date, format: :short %></td>
            <td><%= link_to 'Show', audition %></td>
            <td><%= button_to 'Destroy', audition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/auditions/index.html.erb
<h1>Listing auditions</h1>

<table>
  <thead>
    <tr>
      <th>Prosecutor</th>
      <th>Courte</th>
      <th>Turn</th>
      <th>Date</th>
      <th>Month</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @auditions.each do |audition| %>
      <tr>
        <td><%= audition.prosecutor_name %></td>
        <td><%= audition.courte %></td>
        <td><%= audition.turn %></td>
        <td><%= audition.date %></td>
        <td><%= audition.month %></td>
        <td><%= link_to 'Show', audition %></td>
        <td><%= button_to 'Destroy', audition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/auditions/new.html.erb
<h1>Nova Audiência</h1>

<%= render 'form' %>

app/views/auditions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Prosecutor:</strong>
  <%= @audition.prosecutor %>
</p>

<p>
  <strong>Courte:</strong>
  <%= @audition.courte %>
</p>

<p>
  <strong>Turn:</strong>
  <%= @audition.turn %>
</p>

<p>
  <strong>Date:</strong>
  <%= @audition.date %>
</p>

<p>
  <strong>Prosecutor:</strong>
  <%= @audition.prosecutor %>
</p>

<p>
  <strong>Month:</strong>
  <%= @audition.month %>
</p>

<%= link_to 'Edit', edit_audition_path(@audition) %> |
<%= link_to 'Back', auditions_path %>