config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations:      "users/registrations",
      sessions:           "users/sessions",
      passwords:          "users/passwords"
    }

  root to: 'users#sign_in'

  get '/index' => 'home#index', as: :home

  get '/auditions/:year/:month_name'     => 'auditions#filter', as: :filter_audition
  get '/auditions/:year/:month_name/new' => 'auditions#new', as: :new_audition
  resources :auditions, except: :new

  resources :prosecutors
  resources :months
end

app/models/prosecutor.rb
class Prosecutor < ActiveRecord::Base
  belongs_to :user
  has_many :auditions
end

app/controllers/prosecutors_controller.rb
class ProsecutorsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_prosecutor, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @prosecutors = @current_user.prosecutors.all
    respond_with(@prosecutors)
  end

  def show
    respond_with(@prosecutor)
  end

  def new
    @prosecutor = Prosecutor.new
    respond_with(@prosecutor)
  end

  def edit
  end

  def create
    @prosecutor = Prosecutor.new(prosecutor_params)
    @prosecutor.user = @current_user

    @prosecutor.save
    respond_with(@prosecutor)
  end

  def update
    @prosecutor.update(prosecutor_params)
    respond_with(@prosecutor)
  end

  def destroy
    @prosecutor.destroy
    respond_with(@prosecutor)
  end

  private
    def set_prosecutor
      @prosecutor = @current_user.prosecutors.find(params[:id])
    end

    def prosecutor_params
      params.require(:prosecutor).permit(:name)
    end
end

app/helpers/prosecutors_helper.rb
module ProsecutorsHelper
end

app/views/prosecutors/_form.html.erb
<%= form_for(@prosecutor) do |f| %>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prosecutors/edit.html.erb
<h1>Editing prosecutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @prosecutor %> |
<%= link_to 'Back', prosecutors_path %>

app/views/prosecutors/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"> Listando procuradores</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Nome</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @prosecutors.each do |prosecutor| %>
          <tr>
            <td><%= prosecutor.name %></td>
            <td><%= link_to 'Show', prosecutor %></td>
            <td><%= link_to 'Edit', edit_prosecutor_path(prosecutor) %></td>
            <td><%= link_to 'Destroy', prosecutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= button_to 'Adicionar', new_prosecutor_path, class: 'btn btn-success', method: :get %>

app/views/prosecutors/new.html.erb
<h1>Novo Procurador</h1>

<%= render 'form' %>

app/views/prosecutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prosecutor.name %>
</p>

<%= link_to 'Edit', edit_prosecutor_path(@prosecutor) %> |
<%= link_to 'Back', prosecutors_path %>