config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations:      "users/registrations",
      sessions:           "users/sessions",
      passwords:          "users/passwords"
    }

  root to: 'users#sign_in'

  get '/index' => 'home#index', as: :home

  get '/auditions/:year/:month_name'     => 'auditions#filter', as: :filter_audition
  get '/auditions/:year/:month_name/new' => 'auditions#new', as: :new_audition
  resources :auditions, except: :new

  resources :prosecutors
  resources :months
end

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <%= link_to "AuditionApp", home_path, class: "navbar-brand" %>
  </div>

  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

  <!-- Top Navigation: Left Menu
  <ul class="nav navbar-nav navbar-left navbar-top-links">
    <li><a href="#"><i class="fa fa-home fa-fw"></i> Website</a></li>
  </ul>
  -->

  <!-- Top Navigation: Right Menu -->
  <ul class="nav navbar-right navbar-top-links">

    <%- if controller.controller_name != 'months' %>
      <li class="dropdown navbar-inverse">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-calendar fa-fw"></i>  <%= !@month.nil? ? @month.name.capitalize : (l @date, format: :month) %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu dropdown-alerts">
          <%- @months.each do |month| %>
            <li>
              <%= link_to filter_audition_path(year: month.year, month_name: month.name) do %>
                <i class="fa fa-thumb-tack fa-fw"></i> <%= month.name.capitalize %>
              <% end %>
            </li>
          <% end %>
        </ul>
        </li>
    <% end %>


    <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <i class="fa fa-user fa-fw"></i> <%= @current_user.email %> <b class="caret"></b>
    </a>
    <ul class="dropdown-menu dropdown-user">
      <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
      </li>
      <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
      </li>
      <li class="divider"></li>
      <li>
        <%= button_to destroy_user_session_path, class: "btn btn-md col-lg-12", method: :delete do %>
          <i class="fa fa-sign-out fa-fw"></i> Logout
        <% end %>
      </li>
    </ul>
    </li>
  </ul>

  <%= render 'layouts/sidebar' %>
</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div class="navbar-default sidebar" role="navigation">
  <div class="sidebar-nav navbar-collapse">

    <ul class="nav" id="side-menu">
      <li class="sidebar-search">
      <div class="input-group custom-search-form">
        <input type="text" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </div>
      </li>
      <li>
        <%= link_to home_path, class: 'active' do %>
          <i class="fa fa-home fa-fw"></i> Início
        <% end %>
      </li>

      <%- if controller.controller_name == 'home'%>
        <li>
          <a href="#"><i class="fa fa-list fa-fw"></i> Ver agendamentos<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <%- @months.each do |month| %>
              <li>
                <%= link_to filter_audition_path(month_name: month.name, year: @year ), class: 'active' do %>
                  <i class="fa fa-hand-o-right fa-fw"></i> <%= month.name.capitalize %>
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      <% end %>

      <li>
      <a href="#"><i class="fa fa-plus-circle fa-fw"></i> Cadastrar Audiência<span class="fa arrow"></span></a>
      <ul class="nav nav-second-level">
          <%- @months.each do |month| %>
            <li>
              <%= link_to new_audition_path(year: month.year, month_name: month.name) do %>
                <i class="fa fa-plus-square-o fa-fw"></i> <%= month.name.capitalize %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </li>

      <li>
        <%= link_to months_path do %>
          <i class="fa fa-plus-square-o fa-fw"></i> Adicionar novo Mês
        <% end %>
      </li>

      <li>
        <%= link_to prosecutors_path do %>
          <i class="fa fa-plus-square-o fa-fw"></i> Adicionar novo Procurador
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuditionApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/unsigned.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuditionApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>